name: "Get authenticated user"
description: "Action to get the authenticated user informations. If none return GitHub action bot. Usefull to commit, comment, etc."
author: Hoverkraft
branding:
  icon: user-check
  color: gray-dark

inputs:
  private-access-token:
    description: "GitHub private access token to get authenticated user informations. See https://docs.github.com/en/rest/reference/users#get-the-authenticated-user"

outputs:
  email:
    description: "The GitHub Actions bot user email."
    value: "${{ steps.get-user-infos.outputs.email || '41898282+github-actions[bot]@users.noreply.github.com' }}"
  name:
    description: "The GitHub Actions bot user name."
    value: "${{ steps.get-user-infos.outputs.name || 'github-actions[bot]' }}"

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: get-user-infos
      if: inputs.private-access-token
      with:
        github-token: ${{ inputs.private-access-token }}
        script: |
          const { name, email } = await github.rest.users.getAuthenticated();
          core.setOutput("name", name);
          core.setOutput("email", email);
