name: "Create and merge Pull Request"
description: "Action to create and merge Pull Request. Opinionated, set Github Actions bot as author."
author: Hoverkraft
branding:
  icon: git-pull-request
  color: gray-dark

inputs:
  private-access-token:
    description: "GitHub private access token for creating and merging pull request. See https://github.com/juliangruber/merge-pull-request-action"
    required: true
  branch:
    description: "The pull request branch name"
    required: true
  title:
    description: "The pull request title"
    required: true
  body:
    description: "The pull request body"
    required: true
  commit-message:
    description: "The commit message for the pull request"
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/github-script@v6
      id: authenticated-user
      if: inputs.private-access-token
      with:
        script: |
          core.setOutput("name","hoverkraft-bot[bot]");
          core.setOutput("email", "128996893+hoverkraft-bot[bot]@users.noreply.github.com");

    - uses: peter-evans/create-pull-request@v4.2.4
      id: create-pull-request
      with:
        token: ${{ inputs.private-access-token }}
        signoff: true
        base: ${{ github.event.repository.default_branch }}
        delete-branch: true
        branch: ${{ inputs.branch }}
        title: ${{ inputs.title }}
        body: ${{ inputs.body }}
        commit-message: ${{ inputs.commit-message }}
        author: ${{ steps.authenticated-user.outputs.name }} <${{ steps.authenticated-user.outputs.email }}>
        committer: ${{ steps.authenticated-user.outputs.name }} <${{ steps.authenticated-user.outputs.email }}>

    - name: Merge pull request
      if: steps.create-pull-request.outputs.pull-request-number && steps.create-pull-request.outputs.pull-request-operation != 'closed'
      shell: bash
      run: gh pr merge -R "${{ github.repository }}" --merge --admin "${{ steps.create-pull-request.outputs.pull-request-number }}"
      env:
        GH_TOKEN: ${{ inputs.private-access-token }}
